---
##########################################################
# Prometheus
# Doc: https://github.com/cloudalchemy/ansible-prometheus
##########################################################
prometheus_web_listen_address: "localhost:9090"
prometheus_scrape_configs:
  - job_name: "prometheus"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: "node"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/node.yml"
    basic_auth:
      username: 'node_exporter_user'
      password: '{{ lookup("file", secret
                           + "/node_exporter/"
                           + monitor_group
                           + "/node_exporter_user") }}'
    scheme: https
    tls_config:
      ca_file: '/etc/pki/realms/domain/CA.crt'

# Need to be set, otherwise 'CloudAlchemy/ansible-prometheus : configure prometheus' will fail
prometheus_alertmanager_config: ''

############################################################
# Alertmanager
# Doc: https://github.com/cloudalchemy/ansible-alertmanager
############################################################
alertmanager_web_listen_address: "localhost:9093"
alertmanager_receivers:
  - name: 'dummy_receiver'
alertmanager_route:
  receiver: 'dummy_receiver'

#######################################################
# Grafana
# Doc: https://github.com/cloudalchemy/ansible-grafana
#######################################################
grafana_port: 80
grafana_cap_net_bind_service: true
grafana_security:
  admin_user: 'admin'
  admin_password: '{{ lookup("password", secret
                   + "/grafana/"
                   + inventory_hostname
                   + "/admin_password"
                   + " length=64 chars=ascii_letters,digits") }}'

grafana_datasources:
  - name: Prometheus
    type: prometheus
    url: 'http://localhost:9090'
    basicAuth: false

grafana_dashboards:
  - dashboard_id: 1860
    revision_id: 21
    datasource: Prometheus
